### ISSUE TITLE
Ensure that all commit Comments are Meaningful

### ISSUE THREAD

**Issue by kevindeslauriers** [Jesefu/Zork_1_0_0#2]
Hi Guys,

Can you ensure that all of your commit comments and any issues you place/create are meaningful and contain all of the important information.

Once you have read this please add assign this to a new member of your group and add a comment that you have read this.

Thanks!

DesLauriers

**Comment by Jesefu** [comment]
Read

**Comment by SeanKalirai** [comment]
readed

**Comment by EthanAtkinson** [comment]
read
